change syntax of /etc/init.d/redmine

diff --git a/init/redmine b/init/redmine
--- a/init/redmine
+++ b/init/redmine
@@ -14,14 +14,37 @@
 # based off of thin init script
 
 # Do NOT "set -e"
+USERNAME=$2
+ACTION=$1
 
 SCRIPT_NAME=/etc/init.d/redmine
-APP_ROOT=/var/sites/redmine-$1/current/redmine-trunk
+APP_ROOT=/var/sites/redmine-$USERNAME/current
 __BUNDLE_PATH=bundle
-CONFIG_PATH=/etc/thin/redmine-$1.yml
+CONFIG_PATH=/etc/thin/redmine-$USERNAME.yml
 RVM_SCRIPT=/usr/local/rvm/scripts/rvm
 RVM_PATH=rvm
 THIN_PATH=/usr/bin/thin
+
+usage(){
+  echo "Usage: $0 {start|stop|restart} <username>" >&2
+}
+
+if [[ "$1" == "" ]] || [[ "$1" == "-h" ]] ; then
+  usage
+  exit 0
+fi
+
+if [[ "$1" == -* ]] ; then
+  echo "Invalid option: $1" >&2
+  usage
+  exit 3
+fi
+
+if [[ "$2" == "" ]] ; then
+  echo "Username not provided.  For now, no assumptions made." >&2
+  usage
+  exit 3
+fi
 
 if [ ! -f "$CONFIG_PATH" ] ; then
   echo "Config not found: $CONFIG_PATH" >&2
@@ -54,7 +77,7 @@ if [  "0" -ne "$STATUS" ] ; then
   exit 3
 fi
 
-case "$2" in
+case "$ACTION" in
   start)
   $__BUNDLE_PATH exec $THIN_PATH -C $CONFIG_PATH start
 	;;
@@ -66,7 +89,7 @@ case "$2" in
   $__BUNDLE_PATH exec $THIN_PATH -C $CONFIG_PATH restart
 	;;
   *)
-	echo "Usage: $SCRIPT_NAME <redmine-name> {start|stop|restart}" >&2
+  usage
 	exit 3
 	;;
 esac
